=== Tatsh/freeband/src/io/fbnotes.dtd
<!-- Freeband song format DTD
  NOTE: Changing parts of this, such as the note timings, will NOT affect Freeband functionality. This file is for validation purposes ONLY. -->

<!ELEMENT freebandNotes (artist, title, album*, tier, bpm, gap, samplestart, samplelength, guitar*, bass*, drums*, vocals*, bgm*, notes*, lyrics)>

<!-- Song information -->
<!ELEMENT artist (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT album (#PCDATA)>
<!ELEMENT tier (#PCDATA)>
<!ELEMENT bpm (#PCDATA)>
<!ELEMENT gap (#PCDATA)>
<!ATTLIST gap type (ms|s) "ms">
<!ELEMENT samplestart (#PCDATA)>
<!ATTLIST samplestart type (ms|s) "s">
<!ELEMENT samplelength (#PCDATA)>
<!ATTLIST samplelength type (ms|s) "s">

<!-- Sound files -->
<!ELEMENT guitar (#PCDATA)>
<!ELEMENT bass (#PCDATA)>
<!ELEMENT drums (#PCDATA)>
<!ELEMENT vocals (#PCDATA)>
<!ELEMENT bgm (#PCDATA)>

<!-- Notes -->
<!ELEMENT notes (#PCDATA|gr|fth|tfth|sth|tfrth|tsnd|sfth|tr|f|h|p|w)*>
<!ATTLIST notes type (guitar|bass|drums|vocals) #REQUIRED>
<!ATTLIST notes difficulty (easy|medium|hard|expert) #REQUIRED>
<!ELEMENT gr (#PCDATA|fth|tfth|sth|tfrth|tsnd|sfth|tr|f|h|p|w)*> <!-- grouped notes -->
<!ELEMENT fth (#PCDATA|gr|tfth|sth|tfrth|tsnd|sfth|tr|f|h|p|w)*> <!-- quarter notes -->
<!ELEMENT tfth (#PCDATA|gr|fth|sth|tfrth|tsnd|sfth|tr|f|h|p|w)*> <!-- 12th notes -->
<!ELEMENT sth (#PCDATA|gr|fth|tfth|tfrth|tsnd|sfth|tr|f|h|p|w)*> <!-- 16th notes -->
<!ELEMENT tfrth (#PCDATA|gr|fth|tfth|sth|tsnd|sfth|tr|f|h|p|w)*> <!-- 24th notes -->
<!ELEMENT tsnd (#PCDATA|gr|fth|tfth|sth|tfrth|sfth|tr|f|h|p|w)*> <!-- 32nd notes -->
<!ELEMENT sfth (#PCDATA|gr|fth|tfth|sth|tfrth|tsnd|tr|f|h|p|w)*> <!-- 64th notes -->
<!ELEMENT tr (#PCDATA|gr|fth|tfth|sth|tfrth|tsnd|sfth|f|h|p|w)*> <!-- triplets, which can be within any of the above -->
<!ELEMENT f (#PCDATA|gr|fth|tfth|sth|tfrth|tsnd|sfth|tr|h|p|w)*> <!-- freeze notes -->
<!ELEMENT h (#PCDATA|gr|fth|tfth|sth|tfrth|tsnd|sfth|tr|f|p|w)*> <!-- hammer on -->
<!ELEMENT p (#PCDATA|gr|fth|tfth|sth|tfrth|tsnd|sfth|tr|f|h|w)*> <!-- energy/star power -->
<!ELEMENT w (#PCDATA)> <!-- wail (from GFDM), which is always 1 note, so it may not have anything between -->

<!-- Lyrics -->
<!ELEMENT lyrics (tone*)>
<!ELEMENT tone (#PCDATA)>
<!ATTLIST tone note CDATA #REQUIRED>

=== Tatsh/freeband/songs/Freeband/Dummy/dummy.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE freebandNotes SYSTEM "/home/tatsh/dev/freeband2/src/io/fbnotes.dtd">
<!-- proposed Freeband XML song format -->
<freebandNotes>

  <artist>Dummy Artist</artist>
  <title>Dummy Song</title>
  <album>Dummy Album</album>
  <tier>1</tier>
  <bpm>125.000</bpm>
  <gap type="ms">533</gap>
  <samplestart type="s">30.543</samplestart>
  <samplelength type="s">30.000</samplelength>

  <guitar>Dummy-guitar.ogg</guitar>
  <bass>Dummy-bass.ogg</bass>
  <drums>Dummy-drums.ogg</drums>
  <vocals>Dummy-vocals.ogg</vocals>
  <bgm>Dummy-bgm.ogg</bgm>

  <!--
All songs must start with a freebandNotes tag and end with one.

album is an optional tag. It also can be written as <album /> for no data.
tier is the level of difficulty from 1-10 overall. Freeband has 10 tiers, similar to Guitar Hero and Rock Band's tiers. 1 is easiest, 10 is hardest. 10 will make a song go into an "Impossible Songs"-like tier.
gap, samplestart, and samplelength support type="ms" and type="s" for milliseconds and seconds, respectively. Default for gap is ms. Default for samplestart and samplelength is s.

guitar, bass, drums, vocals, and bgm tags are optional but are recommended. If they are not found, Freeband will look for files in the following way:

To find the BGM: Folder name/Folder name-bgm.Sound format that Freeband supports
To find the guitar: Folder name/Folder name-guitar.Sound format that Freeband supports
etc

You may specify to only have a BGM and no other tracks (like many songs on hacked GH2 games) by placing only a BGM in the folder and no other audio files. ANY file (with a sound format supported) within the folder will become the BGM if there is only ONE file. It does NOT need to be named Folder name-bgm.Sound format that Freeband supports.

Notation:

notes tag is mandatory and it MUST specify type of notes and difficulty. Guitar, bass, drums, and vocals are currently the only valid tags for type. Easy, medium, hard, expert (in any cAsInG) are the only valid tags for difficulty. If a song has any of these misspelt, not listed, or incorrect, that note set of the song will NOT load.

0 = no note
1 = green
2 = red
3 = yellow
4 = blue
5 = orange

By default, every note is an 8th note. To group notes, use gr around them, for example: (135) for green, red, and orange at once.

To make things easier, you may use fth around quarter notes.

For 12th notes, use tfth around the notes. For 16th notes, use sth. For 24th notes, use tfrth. For 32nd notes, use tsnd. Lastly for 64th notes, use sfth. Arbitrary values are NOT allowed and will be ignored.

For triplets, which may be within any type of note timing, use tr.

Freeband will not fill in the rest of the timing, so make sure zeros are at the end of the stream if necessary.

To make a hammer on note, use h around the notes. For example, <sth>4<h>2</h></sth> tells Freeband to render 16th notes and make the red button a hammer on.

To make an energy/star power note set, place p around the note set. For wail on GFDM songs, use w.

For freezes, use f around the note until the end of it using zeros. For example, to tell Freeband to make a freeze for 1 bar on the green button use: <f>10000000</f> or you may use <fth><f>1000</f></fth>.

Drums have a special 6th note, the kick, which is specified by the letter k.

This should cover almost every case. The DTD will continue to be updated. If you change the DTD, this does not mean Freeband will understand the changes. The DTD is only for validation and will not change any Freeband functionality. For that you must change the source.

Vocals format is defined below.

As always with XML, you can make notes like this anywhere within the document.
-->

  <notes type="guitar" difficulty="easy">
  </notes>

  <notes type="guitar" difficulty="medium">
  </notes>

  <notes type="guitar" difficulty="hard">
  </notes>

  <notes type="guitar" difficulty="expert">
113<h>2</h>
1130
113<h>2</h>
1130
    <p>113<h>2</h>
1130
1140
11<w>4</w>0</p>
    <f>10000000</f>
  </notes>

  <notes type="bass" difficulty="easy">
  </notes>

  <notes type="bass" difficulty="medium">
  </notes>

  <notes type="bass" difficulty="hard">
  </notes>

  <notes type="bass" difficulty="expert">
  </notes>

  <notes type="drums" difficulty="easy">
  </notes>

  <notes type="drums" difficulty="medium">
  </notes>

  <notes type="drums" difficulty="hard">
  </notes>

  <notes type="drums" difficulty="expert">
    <fth>
4444</fth>

    <gr>k2</gr>0
    <gr>12</gr>2
    <gr>12</gr>2
    <gr>12</gr>2
    <p>
      <gr>12</gr>2
      <gr>k2</gr>0</p>
    <gr>12</gr>2
    <gr>12</gr>2
    <gr>12</gr>2
    <gr>12</gr>
    <sth>2<w>2</w>
    </sth>

    <tfth>
      <tr>
44<p>4</p>
      </tr>
    </tfth>
  </notes>

  <lyrics>
    <tone note="C3">This is a</tone>
    <tone note="A#3">dummy file</tone>
  </lyrics>

  <!-- Lyrics require at least ONE <tone> tag surround lyrics. For lyrics to validate, all lyrics within <lyrics> MUST have a <tone> tag surrounding them or the vocals will not load. Freeband can use notes from C1 to C10. -->

</freebandNotes>
