=== Tatsh/freeband/src/io/fbprefs.dtd
<!-- Freeband prefs format DTD
  NOTE: Freeband will probably NOT load correctly if this file is modified -->

<!ELEMENT freebandPrefs (appearance, game, input, graphics, online, songs)>

<!ELEMENT appearance (audience, band, theme)>
<!ELEMENT audience EMPTY>
<!ATTLIST audience enabled (true|false) "true">
<!ELEMENT band EMPTY>
<!ATTLIST band enabled (true|false) "true">
<!ELEMENT theme (#PCDATA)>

<!ELEMENT game (difficulty)>
<!ELEMENT difficulty EMPTY>
<!ATTLIST difficulty judge (1|2|3|4|5|6|7|8|9|10) "5">

<!ELEMENT input (controller*)>
<!ELEMENT controller (button*, axis*)>
<!ATTLIST controller type (keyboard|joystick|microphone) "keyboard">
<!ATTLIST controller hwid CDATA "0x0000">
<!ATTLIST controller player (1|2|3|4) #REQUIRED>
<!ATTLIST controller enabled (true|false) #REQUIRED>
<!ELEMENT button (#PCDATA)>
<!ATTLIST button type (green|red|yellow|blue|orange|start|select|pick_up|pick_down|direction_down|direction_up|direction_left|direction_right|energy|whammy_down|whammy_up) #REQUIRED>
<!ELEMENT axis (#PCDATA)>
<!ATTLIST axis type (energy|whammy) #REQUIRED>
<!ATTLIST axis enabled (true|false) #REQUIRED>

<!ELEMENT graphics (resolution, colour, texture)>
<!ELEMENT resolution EMPTY>
<!ATTLIST resolution width (800|1024|1280|1440|1600|1920|2048) "800">
<!ATTLIST resolution height (600|768|800|1024|900|1200|1080|1536) "600">
<!ELEMENT colour EMPTY>
<!ATTLIST colour bitdepth (16|24|32) "32">
<!ELEMENT texture EMPTY>
<!ATTLIST texture size (512|1024|2048) "2048">

<!ELEMENT online (time_limit)>
<!ELEMENT time_limit EMPTY>
<!ATTLIST time_limit enabled (true|false) "false">
<!ATTLIST time_limit time (30|60|90|120|unlimited) "90">

<!ELEMENT songs (options, speed_per_title, default_speed_mod)>
<!ELEMENT options EMPTY>
<!ATTLIST options menu (true|false) "true">
<!ATTLIST options button (none|green|red|yellow|blue|orange|start|select) "start">
<!ELEMENT speed_per_title EMPTY>
<!ATTLIST speed_per_title enabled (true|false) "true">
<!ELEMENT default_speed_mod EMPTY>
<!ATTLIST default_speed_mod speed CDATA "0">

=== Tatsh/freeband/src/io/preferences.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE freebandPrefs SYSTEM "/home/tatsh/dev/freeband/src/io/fbprefs.dtd">

<freebandPrefs>
  
  <appearance>
    <audience enabled="true" />
    <band enabled="true" />
    <theme>default</theme>
  </appearance>

  <game>
    <difficulty judge="5" />
  </game>
  
  <input>
    <controller type="keyboard" hwid="0x0000" player="1" enabled="true">
      <button type="green">F1</button>
      <button type="red">F2</button>
      <button type="yellow">F3</button>
      <button type="blue">F4</button>
      <button type="orange">F5</button>
      <button type="start">RETURN</button>
      <button type="select">RSHIFT</button>
      <button type="energy">I</button>
      <button type="whammy_down">O</button>
      <button type="whammy_up">P</button>
      <button type="pick_up">ALWAYS</button>
      <button type="pick_down">ALWAYS</button>
      <button type="direction_down">DOWN</button>
      <button type="direction_up">UP</button>
      <button type="direction_left">LEFT</button>
      <button type="direction_right">RIGHT</button>
    </controller>
    
    <controller type="keyboard" hwid="0x0000" player="2" enabled="false">
    </controller>
    
    <controller type="keyboard" hwid="0x0000" player="3" enabled="false">
    </controller>
    
    <controller type="microphone" hwid="0x0000" player="4" enabled="true"/>
    
    <!-- Xbox 360 controller with Linux driver -->
    <controller type="joystick" hwid="0x0000" player="1" enabled="true">
      <button type="green">7</button>
      <button type="red">8</button>
      <button type="yellow">9</button>
      <button type="blue">10</button>
      <button type="orange">11</button>
      <button type="start">0</button>
      <button type="select">1</button>
      <button type="pick_up">2</button>
      <button type="pick_down">3</button>
      <button type="direction_down">12</button>
      <button type="direction_up">13</button>
      <button type="direction_left">14</button>
      <button type="direction_right">15</button>
      <axis type="energy" enabled="true">1</axis>
      <axis type="whammy" enabled="true">2</axis>
    </controller>
    
    <controller type="joystick" hwid="0x0000" player="2" enabled="false">
    </controller>
    
    <controller type="joystick" hwid="0x0000" player="3" enabled="false">
    </controller>
    
  </input>

  <graphics>
    <resolution width="800" height="600" />
    <colour bitdepth="32" />
    <texture size="2048" />
  </graphics>
  
  <online>
    <time_limit enabled="false" time="90" /> <!-- Amount of time users have to pick their set list -->
  </online>
  
  <songs>
    <options menu="true" button="start" />
    <speed_per_title enabled="false" />
    <default_speed_mod speed="0" />
  </songs>

</freebandPrefs>
